/**
 * AI Narrative Block — LLM-generated insight paragraph with loading state.
 *
 * Used in: Dashboard Direct, Audience Comparison Direct, Channel Health Direct.
 * Fetches from /api/narrative/generate, shows skeleton while loading.
 */

import { motion } from "framer-motion";
import { Sparkles } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";
import { MOTION_DURATION, MOTION_EASING } from "@/lib/motion-config";
import { cn } from "@/lib/utils";

interface AINarrativeBlockProps {
  narrative?: string;
  isLoading?: boolean;
  usedAI?: boolean;
  variant?: "default" | "verdict" | "compact";
  className?: string;
}

export function AINarrativeBlock({
  narrative,
  isLoading = false,
  usedAI = false,
  variant = "default",
  className,
}: AINarrativeBlockProps) {
  if (isLoading) {
    return (
      <div className={cn("space-y-2", className)}>
        <Skeleton className="h-4 w-full" />
        <Skeleton className="h-4 w-4/5" />
        {variant !== "compact" && <Skeleton className="h-4 w-3/5" />}
      </div>
    );
  }

  if (!narrative) return null;

  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: MOTION_DURATION.ui, ease: MOTION_EASING.out }}
      className={cn(
        "relative",
        variant === "verdict" && "rounded-lg border bg-muted/30 p-4",
        variant === "compact" && "text-sm",
        className
      )}
    >
      {variant === "verdict" && (
        <div className="mb-2 flex items-center gap-1.5 text-xs font-medium text-muted-foreground">
          <Sparkles className="h-3 w-3" style={{ color: "var(--catalyst-gold, #d97706)" }} />
          <span>AI Analysis</span>
        </div>
      )}

      <p
        className={cn(
          "leading-relaxed text-foreground/90",
          variant === "default" && "text-sm",
          variant === "verdict" && "text-sm font-medium",
          variant === "compact" && "text-xs text-muted-foreground"
        )}
      >
        {narrative}
      </p>

      {usedAI && variant !== "compact" && (
        <div className="mt-2 flex items-center gap-1 text-[10px] text-muted-foreground/60">
          <Sparkles className="h-2.5 w-2.5" />
          <span>Generated by AI</span>
        </div>
      )}
    </motion.div>
  );
}
